//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_OrionTek.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.direcciones = new HashSet<direccione>();
            this.logs = new HashSet<log>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "The name field cannot be empty")]
        [MinLength(3, ErrorMessage = "The name field should have more than 4 characters")]
        public string nombre { get; set; }

        [Required(ErrorMessage = "The last name field cannot be empty")]
        [MinLength(3, ErrorMessage = "The last name field should have more than 4 characters")]
        public string apellido { get; set; }

        [Required(ErrorMessage = "The phone field cannot be empty")]
        [MinLength(10, ErrorMessage = "The phone field should have 10 digits")]
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direccione> direcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> logs { get; set; }
    }
}
