//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_OrionTek.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccione
    {
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string line1 { get; set; }
        public string line2 { get; set; }
        public string sector { get; set; }
        public string ciudad { get; set; }
        public Nullable<int> zipcode { get; set; }
        public Nullable<int> id_pais { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual pais pais1 { get; set; }
    }
}
